export const usersMock = [
  {
    _id: '5fe1933e71260abb214c869e',
    isActive: false,
    balance: '$1,942.91',
    picture: 'http://placehold.it/32x32',
    age: 30,
    name: {
      first: 'Candice',
      last: 'Mack',
    },
    company: 'COMBOGENE',
    email: 'candice.mack@combogene.info',
    address: '491 Pine Street, Wawona, Oklahoma, 2443',
    tags: ['fugiat', 'duis', 'nisi', 'veniam', 'officia'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e5f049e9dcb034095',
    isActive: true,
    balance: '$3,203.94',
    picture: 'http://placehold.it/32x32',
    age: 32,
    name: {
      first: 'Avis',
      last: 'Buchanan',
    },
    company: 'MANTRIX',
    email: 'avis.buchanan@mantrix.tv',
    address: '468 Howard Avenue, Cherokee, Missouri, 2714',
    tags: ['ea', 'anim', 'proident', 'aliqua', 'est'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e64b818c1d7d66f1b',
    isActive: true,
    balance: '$2,446.31',
    picture: 'http://placehold.it/32x32',
    age: 35,
    name: {
      first: 'Henderson',
      last: 'Hooper',
    },
    company: 'UPLINX',
    email: 'henderson.hooper@uplinx.name',
    address: '780 Glendale Court, Tampico, South Carolina, 2733',
    tags: ['nostrud', 'esse', 'consectetur', 'ut', 'nisi'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e2473d054b31c6048',
    isActive: false,
    balance: '$3,028.51',
    picture: 'http://placehold.it/32x32',
    age: 32,
    name: {
      first: 'Foley',
      last: 'Fitzgerald',
    },
    company: 'UNCORP',
    email: 'foley.fitzgerald@uncorp.biz',
    address: '461 Vanderbilt Street, Foxworth, Colorado, 9896',
    tags: ['commodo', 'exercitation', 'anim', 'pariatur', 'officia'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e65b371e154ce7682',
    isActive: false,
    balance: '$2,755.24',
    picture: 'http://placehold.it/32x32',
    age: 26,
    name: {
      first: 'Griffith',
      last: 'Knight',
    },
    company: 'ENDIPIN',
    email: 'griffith.knight@endipin.io',
    address: '418 Lloyd Court, Turah, Kentucky, 9586',
    tags: ['anim', 'consectetur', 'magna', 'veniam', 'magna'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933eaf2342fdc18e1fe4',
    isActive: false,
    balance: '$3,598.38',
    picture: 'http://placehold.it/32x32',
    age: 22,
    name: {
      first: 'Richardson',
      last: 'Lara',
    },
    company: 'MAZUDA',
    email: 'richardson.lara@mazuda.biz',
    address: '836 Dakota Place, Movico, Virginia, 6240',
    tags: ['anim', 'sunt', 'velit', 'nulla', 'occaecat'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e6510d84c160ccda8',
    isActive: true,
    balance: '$2,531.89',
    picture: 'http://placehold.it/32x32',
    age: 22,
    name: {
      first: 'Kaye',
      last: 'Meyers',
    },
    company: 'FURNIGEER',
    email: 'kaye.meyers@furnigeer.net',
    address: '761 Lawn Court, Sunnyside, Minnesota, 6973',
    tags: ['eu', 'duis', 'qui', 'est', 'proident'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933eafc7060ef888862d',
    isActive: false,
    balance: '$1,693.10',
    picture: 'http://placehold.it/32x32',
    age: 26,
    name: {
      first: 'Allen',
      last: 'Small',
    },
    company: 'ANIMALIA',
    email: 'allen.small@animalia.com',
    address: '294 Anthony Street, Westwood, Alabama, 7161',
    tags: ['do', 'velit', 'exercitation', 'nostrud', 'exercitation'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933ec635d5efce663942',
    isActive: false,
    balance: '$2,836.62',
    picture: 'http://placehold.it/32x32',
    age: 24,
    name: {
      first: 'Chavez',
      last: 'Valencia',
    },
    company: 'XERONK',
    email: 'chavez.valencia@xeronk.me',
    address: '659 Cooper Street, Grazierville, Guam, 2532',
    tags: ['dolore', 'id', 'dolore', 'ad', 'sit'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e8d52814f435d39a1',
    isActive: false,
    balance: '$3,408.37',
    picture: 'http://placehold.it/32x32',
    age: 22,
    name: {
      first: 'Cheri',
      last: 'Cooke',
    },
    company: 'RECRISYS',
    email: 'cheri.cooke@recrisys.co.uk',
    address: '642 Sackman Street, Blanco, Indiana, 9877',
    tags: ['est', 'magna', 'ex', 'tempor', 'duis'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933ef5108fe0ed91e263',
    isActive: true,
    balance: '$3,321.21',
    picture: 'http://placehold.it/32x32',
    age: 22,
    name: {
      first: 'Black',
      last: 'Molina',
    },
    company: 'METROZ',
    email: 'black.molina@metroz.org',
    address: '685 Baycliff Terrace, Longoria, Nevada, 6702',
    tags: ['aute', 'ullamco', 'cillum', 'esse', 'aliquip'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e41fed91d52cc4aff',
    isActive: true,
    balance: '$3,521.51',
    picture: 'http://placehold.it/32x32',
    age: 21,
    name: {
      first: 'Spears',
      last: 'Farrell',
    },
    company: 'GORGANIC',
    email: 'spears.farrell@gorganic.ca',
    address: '772 Covert Street, Kenvil, Florida, 8064',
    tags: ['exercitation', 'adipisicing', 'adipisicing', 'nisi', 'laborum'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e7859f473429b8432',
    isActive: false,
    balance: '$1,694.21',
    picture: 'http://placehold.it/32x32',
    age: 36,
    name: {
      first: 'Mayo',
      last: 'Leon',
    },
    company: 'COMVEYOR',
    email: 'mayo.leon@comveyor.info',
    address: '915 Lorraine Street, Wildwood, Mississippi, 5011',
    tags: ['tempor', 'quis', 'duis', 'aliquip', 'culpa'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e745519be317b32bd',
    isActive: false,
    balance: '$3,095.96',
    picture: 'http://placehold.it/32x32',
    age: 29,
    name: {
      first: 'Guerrero',
      last: 'Keller',
    },
    company: 'COMSTRUCT',
    email: 'guerrero.keller@comstruct.tv',
    address: '248 Beaver Street, Floriston, American Samoa, 387',
    tags: ['irure', 'eu', 'nulla', 'laboris', 'dolor'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933eba60020bb7a6537b',
    isActive: false,
    balance: '$3,050.77',
    picture: 'http://placehold.it/32x32',
    age: 20,
    name: {
      first: 'Blanche',
      last: 'Weaver',
    },
    company: 'FUTURIS',
    email: 'blanche.weaver@futuris.name',
    address: '906 Brightwater Avenue, Roland, Alaska, 1283',
    tags: ['pariatur', 'labore', 'deserunt', 'nulla', 'deserunt'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933eb9d9272dc98251f8',
    isActive: true,
    balance: '$2,673.81',
    picture: 'http://placehold.it/32x32',
    age: 38,
    name: {
      first: 'Barton',
      last: 'Cotton',
    },
    company: 'KROG',
    email: 'barton.cotton@krog.biz',
    address: '107 Junius Street, Glendale, Massachusetts, 8573',
    tags: ['id', 'reprehenderit', 'incididunt', 'sint', 'labore'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e300c422721e0642d',
    isActive: true,
    balance: '$3,339.07',
    picture: 'http://placehold.it/32x32',
    age: 29,
    name: {
      first: 'Rose',
      last: 'Waters',
    },
    company: 'MAGNEMO',
    email: 'rose.waters@magnemo.io',
    address: '487 Allen Avenue, Frystown, New Mexico, 9825',
    tags: ['esse', 'ut', 'consequat', 'laborum', 'aute'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e342a3d42160159f0',
    isActive: false,
    balance: '$1,489.57',
    picture: 'http://placehold.it/32x32',
    age: 39,
    name: {
      first: 'Cole',
      last: 'Kent',
    },
    company: 'GRONK',
    email: 'cole.kent@gronk.biz',
    address: '771 Garfield Place, Hachita, District Of Columbia, 9185',
    tags: ['dolore', 'enim', 'magna', 'deserunt', 'nostrud'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e3271905be7c1566d',
    isActive: true,
    balance: '$2,534.37',
    picture: 'http://placehold.it/32x32',
    age: 23,
    name: {
      first: 'Queen',
      last: 'Malone',
    },
    company: 'ELITA',
    email: 'queen.malone@elita.net',
    address: '502 Morton Street, Edmund, Maine, 2519',
    tags: ['mollit', 'irure', 'veniam', 'irure', 'voluptate'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e33a492d6d4989b48',
    isActive: false,
    balance: '$3,833.41',
    picture: 'http://placehold.it/32x32',
    age: 25,
    name: {
      first: 'Frederick',
      last: 'Boyd',
    },
    company: 'ZILCH',
    email: 'frederick.boyd@zilch.com',
    address: '313 Ditmars Street, Newry, Marshall Islands, 5803',
    tags: ['ea', 'do', 'pariatur', 'anim', 'laboris'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933ecbe11baa0f8c4656',
    isActive: false,
    picture: 'http://placehold.it/32x32',
    age: 39,
    name: {
      first: 'Cunningham',
      last: 'Wells',
    },
    company: 'HAIRPORT',
    email: 'cunningham.wells@hairport.me',
    address: '999 Jamaica Avenue, Belva, Vermont, 6343',
    tags: ['culpa', 'eiusmod', 'fugiat', 'nostrud', 'consectetur'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933eb65b640dea0545d2',
    isActive: false,
    balance: '$1,532.63',
    picture: 'http://placehold.it/32x32',
    age: 36,
    name: {
      first: 'James',
      last: 'Terrell',
    },
    company: 'GEOFORM',
    email: 'james.terrell@geoform.co.uk',
    address: '819 Ellery Street, Walker, Oregon, 5964',
    tags: ['anim', 'culpa', 'cupidatat', 'dolor', 'pariatur'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933ecb514a626ca1b87c',
    isActive: true,
    balance: '$3,799.73',
    picture: 'http://placehold.it/32x32',
    age: 38,
    name: {
      first: 'Mona',
      last: 'Bolton',
    },
    company: 'BYTREX',
    email: 'mona.bolton@bytrex.org',
    address: '881 Coleridge Street, Tuskahoma, Ohio, 8707',
    tags: ['nisi', 'velit', 'commodo', 'nulla', 'in'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e5941e6d7a389f1b5',
    isActive: false,
    balance: '$1,727.76',
    picture: 'http://placehold.it/32x32',
    age: 27,
    name: {
      first: 'Tracey',
      last: 'Aguirre',
    },
    company: 'QUINTITY',
    email: 'tracey.aguirre@quintity.ca',
    address: '646 Eldert Street, Outlook, Arkansas, 9865',
    tags: ['elit', 'aute', 'voluptate', 'consequat', 'cupidatat'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e148949b50cda719d',
    isActive: true,
    balance: '$1,014.63',
    picture: 'http://placehold.it/32x32',
    age: 33,
    name: {
      first: 'Lula',
      last: 'Holmes',
    },
    company: 'COMTRAIL',
    email: 'lula.holmes@comtrail.info',
    address: '492 Harbor Lane, Marenisco, Federated States Of Micronesia, 2231',
    tags: ['proident', 'eu', 'consectetur', 'excepteur', 'qui'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e5f9fa65c199bcf04',
    isActive: true,
    balance: '$1,410.35',
    picture: 'http://placehold.it/32x32',
    age: 37,
    name: {
      first: 'Phelps',
      last: 'Weeks',
    },
    company: 'FIBEROX',
    email: 'phelps.weeks@fiberox.tv',
    address: '762 Albee Square, Hannasville, New Hampshire, 4993',
    tags: ['in', 'ex', 'elit', 'Lorem', 'Lorem'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e9ce4034695d48807',
    isActive: true,
    balance: '$1,188.67',
    picture: 'http://placehold.it/32x32',
    age: 22,
    name: {
      first: 'Ora',
      last: 'Whitfield',
    },
    company: 'COMVEX',
    email: 'ora.whitfield@comvex.name',
    address: '286 Chestnut Street, Goodville, Montana, 8115',
    tags: ['sint', 'consectetur', 'labore', 'quis', 'nisi'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e4b0ad54a358f0f0c',
    isActive: true,
    balance: '$2,392.72',
    picture: 'http://placehold.it/32x32',
    age: 29,
    name: {
      first: 'Huber',
      last: 'Snow',
    },
    company: 'PODUNK',
    email: 'huber.snow@podunk.biz',
    address: '683 Borinquen Pl, Lewis, Nebraska, 7955',
    tags: ['non', 'proident', 'exercitation', 'occaecat', 'pariatur'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e3d8464f2de424acc',
    isActive: false,
    balance: '$1,738.98',
    picture: 'http://placehold.it/32x32',
    age: 23,
    name: {
      first: 'Moody',
      last: 'Singleton',
    },
    company: 'ESCHOIR',
    email: 'moody.singleton@eschoir.io',
    address: '849 Oriental Boulevard, Vandiver, Hawaii, 9819',
    tags: ['anim', 'sunt', 'in', 'ex', 'deserunt'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933ebd691349e3da6808',
    isActive: true,
    balance: '$2,163.59',
    picture: 'http://placehold.it/32x32',
    age: 35,
    name: {
      first: 'Ida',
      last: 'Gould',
    },
    company: 'SONGBIRD',
    email: 'ida.gould@songbird.biz',
    address: '589 Schenck Street, Rosedale, Wyoming, 4355',
    tags: ['excepteur', 'reprehenderit', 'deserunt', 'ipsum', 'aute'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933ebf4131b99f65d51a',
    isActive: true,
    balance: '$2,761.18',
    picture: 'http://placehold.it/32x32',
    age: 25,
    name: {
      first: 'Karin',
      last: 'Sanford',
    },
    company: 'SULFAX',
    email: 'karin.sanford@sulfax.net',
    address: '905 Joralemon Street, Nanafalia, Connecticut, 8052',
    tags: ['proident', 'minim', 'excepteur', 'excepteur', 'veniam'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933eb63ef5ba196ad03b',
    isActive: false,
    balance: '$2,704.01',
    picture: 'http://placehold.it/32x32',
    age: 30,
    name: {
      first: 'Barlow',
      last: 'Nunez',
    },
    company: 'MEDCOM',
    email: 'barlow.nunez@medcom.com',
    address: '320 Meserole Street, Roeville, Iowa, 4717',
    tags: ['ut', 'aliquip', 'ullamco', 'enim', 'sunt'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e16de06bb81347878',
    isActive: false,
    balance: '$1,595.08',
    picture: 'http://placehold.it/32x32',
    age: 31,
    name: {
      first: 'Robbins',
      last: 'Cooper',
    },
    company: 'LIQUICOM',
    email: 'robbins.cooper@liquicom.me',
    address: '641 Bath Avenue, Oretta, Illinois, 466',
    tags: ['enim', 'dolor', 'tempor', 'id', 'ipsum'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933ec9badd850a25a847',
    isActive: false,
    balance: '$3,003.33',
    picture: 'http://placehold.it/32x32',
    age: 36,
    name: {
      first: 'Haynes',
      last: 'Humphrey',
    },
    company: 'ZENTURY',
    email: 'haynes.humphrey@zentury.co.uk',
    address: '240 Love Lane, Greenbush, North Dakota, 3588',
    tags: ['eu', 'nisi', 'magna', 'non', 'aliquip'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e6683a3fd5ba58960',
    isActive: true,
    balance: '$2,083.53',
    picture: 'http://placehold.it/32x32',
    age: 36,
    name: {
      first: 'Allison',
      last: 'Tyson',
    },
    company: 'VIDTO',
    email: 'allison.tyson@vidto.org',
    address: '639 Withers Street, Efland, North Carolina, 5891',
    tags: ['id', 'dolor', 'laborum', 'commodo', 'fugiat'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e0b86b2e832005b2e',
    isActive: false,
    balance: '$1,828.10',
    picture: 'http://placehold.it/32x32',
    age: 29,
    name: {
      first: 'Penny',
      last: 'Dorsey',
    },
    company: 'INQUALA',
    email: 'penny.dorsey@inquala.ca',
    address: '333 Grand Avenue, Cartwright, Palau, 3652',
    tags: ['ut', 'laboris', 'non', 'veniam', 'eu'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e74514f566e6eac3a',
    isActive: true,
    balance: '$2,592.93',
    picture: 'http://placehold.it/32x32',
    age: 29,
    name: {
      first: 'Bass',
      last: 'Hill',
    },
    company: 'VORTEXACO',
    email: 'bass.hill@vortexaco.info',
    address: '147 Kingsland Avenue, Terlingua, Puerto Rico, 2885',
    tags: ['exercitation', 'cupidatat', 'adipisicing', 'laboris', 'irure'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933ee9eb294232d1d08f',
    isActive: false,
    balance: '$2,763.34',
    picture: 'http://placehold.it/32x32',
    age: 34,
    name: {
      first: 'Louella',
      last: 'Huff',
    },
    company: 'ISOLOGICA',
    email: 'louella.huff@isologica.tv',
    address: '232 Eckford Street, Forestburg, Maryland, 7061',
    tags: ['aute', 'irure', 'elit', 'fugiat', 'nostrud'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e13fd46279c275613',
    isActive: false,
    balance: '$1,910.17',
    picture: 'http://placehold.it/32x32',
    age: 30,
    name: {
      first: 'Pauline',
      last: 'Frost',
    },
    company: 'XIXAN',
    email: 'pauline.frost@xixan.name',
    address: '680 Berkeley Place, Sterling, Delaware, 9009',
    tags: ['dolore', 'sunt', 'excepteur', 'ullamco', 'dolor'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e6f4293667f203249',
    isActive: true,
    balance: '$2,097.24',
    picture: 'http://placehold.it/32x32',
    age: 26,
    name: {
      first: 'Lou',
    },
    company: 'STUCCO',
    email: 'lou.oneill@stucco.biz',
    address: '416 Pioneer Street, Moscow, Louisiana, 7058',
    tags: ['eu', 'veniam', 'sint', 'consectetur', 'cupidatat'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e575ff7d44710a65b',
    isActive: true,
    balance: '$1,186.23',
    picture: 'http://placehold.it/32x32',
    age: 20,
    name: {
      first: 'Simmons',
      last: 'Pennington',
    },
    company: 'CAPSCREEN',
    address: '509 Knapp Street, Norfolk, Arizona, 5960',
    tags: ['aute', 'qui', 'veniam', 'ad', 'fugiat'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e8c70c7c76f4dd83f',
    isActive: true,
    balance: '$3,447.77',
    picture: 'http://placehold.it/32x32',
    age: 36,
    name: {
      first: 'Lambert',
      last: 'Ellis',
    },
    company: 'QUILTIGEN',
    email: 'lambert.ellis@quiltigen.biz',
    address: '200 Newport Street, Hemlock, South Dakota, 5202',
    tags: ['proident', 'labore', 'Lorem', 'adipisicing', 'ut'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e5691a252dad216c4',
    isActive: true,
    balance: '$3,773.20',
    picture: 'http://placehold.it/32x32',
    age: 36,
    name: {
      first: 'Janet',
      last: 'Barrera',
    },
    company: 'ZOSIS',
    email: 'janet.barrera@zosis.net',
    address: '768 Elliott Walk, Blende, New Jersey, 3377',
    tags: ['anim', 'excepteur', 'est', 'consequat', 'commodo'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e7a70ea3f4ed874e6',
    isActive: true,
    balance: '$1,402.95',
    picture: 'http://placehold.it/32x32',
    age: 29,
    name: {
      first: 'Kent',
      last: 'Ramos',
    },
    company: 'ACCUPRINT',
    email: 'kent.ramos@accuprint.com',
    address: '631 Ivan Court, Loyalhanna, Northern Mariana Islands, 4915',
    tags: ['consectetur', 'deserunt', 'occaecat', 'reprehenderit', 'velit'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933ecf2eeabffdd85d17',
    isActive: true,
    balance: '$1,136.13',
    picture: 'http://placehold.it/32x32',
    age: 28,
    name: {
      first: 'Francesca',
      last: 'Sutton',
    },
    company: 'POLARAX',
    email: 'francesca.sutton@polarax.me',
    address: '845 Fiske Place, Healy, West Virginia, 4411',
    tags: ['do', 'commodo', 'culpa', 'eiusmod', 'commodo'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933eff6a43ab2d3bb7e2',
    isActive: false,
    balance: '$2,121.02',
    picture: 'http://placehold.it/32x32',
    age: 23,
    name: {
      first: 'Aisha',
      last: 'Tyler',
    },
    company: 'FRENEX',
    email: 'aisha.tyler@frenex.co.uk',
    address: '581 Conover Street, Bynum, Washington, 334',
    tags: ['proident', 'nostrud', 'exercitation', 'nostrud', 'voluptate'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e8b9dc7601569b6fc',
    isActive: false,
    balance: '$2,450.48',
    picture: 'http://placehold.it/32x32',
    age: 33,
    name: {
      first: 'Carpenter',
      last: 'Leach',
    },
    company: 'NETBOOK',
    email: 'carpenter.leach@netbook.org',
    address: '337 Monroe Place, Heil, Virgin Islands, 5412',
    tags: ['irure', 'consequat', 'incididunt', 'ipsum', 'esse'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933eb5df771b2c5019d2',
    isActive: true,
    balance: '$3,649.25',
    picture: 'http://placehold.it/32x32',
    age: 38,
    name: {
      first: 'Myers',
      last: 'Duffy',
    },
    company: 'ZOINAGE',
    email: 'myers.duffy@zoinage.ca',
    address: '754 Waldane Court, Farmers, Texas, 4161',
    tags: ['exercitation', 'ex', 'enim', 'mollit', 'ad'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e75cbe63573c3f60b',
    isActive: false,
    balance: '$2,370.18',
    picture: 'http://placehold.it/32x32',
    age: 35,
    name: {
      first: 'Francis',
      last: 'Harrell',
    },
    company: 'HYPLEX',
    email: 'francis.harrell@hyplex.info',
    address: '338 Elton Street, Elliott, California, 7622',
    tags: ['cupidatat', 'cupidatat', 'excepteur', 'nisi', 'exercitation'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e9cc5a0bb919a2fb1',
    isActive: false,
    balance: '$2,830.23',
    picture: 'http://placehold.it/32x32',
    age: 23,
    name: {
      first: 'Tanya',
      last: 'Schwartz',
    },
    company: 'DATACATOR',
    email: 'tanya.schwartz@datacator.tv',
    address: '401 Crooke Avenue, Lacomb, Wisconsin, 1372',
    tags: ['exercitation', 'nulla', 'elit', 'minim', 'et'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e7bc76a62f0718bcb',
    isActive: false,
    balance: '$3,103.76',
    picture: 'http://placehold.it/32x32',
    age: 36,
    name: {
      first: 'Kidd',
      last: 'Ashley',
    },
    company: 'HARMONEY',
    email: 'kidd.ashley@harmoney.name',
    address: '940 Belmont Avenue, Hondah, Idaho, 8169',
    tags: ['Lorem', 'duis', 'fugiat', 'qui', 'id'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e0217f379ce5254b5',
    isActive: false,
    balance: '$3,887.21',
    picture: 'http://placehold.it/32x32',
    age: 28,
    name: {
      first: 'May',
      last: 'Mendez',
    },
    company: 'EARTHPURE',
    email: 'may.mendez@earthpure.biz',
    address: '693 Hicks Street, Strykersville, Pennsylvania, 119',
    tags: ['commodo', 'labore', 'do', 'ea', 'aliqua'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e7a4b44b8c28aeb00',
    isActive: false,
    balance: '$3,735.39',
    picture: 'http://placehold.it/32x32',
    age: 24,
    name: {
      first: 'Erika',
      last: 'Morrow',
    },
    company: 'CENTREXIN',
    email: 'erika.morrow@centrexin.io',
    address: '153 Varanda Place, Gorst, Michigan, 6334',
    tags: ['Lorem', 'non', 'nulla', 'cupidatat', 'amet'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e505dad2cfcfad4f9',
    isActive: false,
    balance: '$1,160.85',
    picture: 'http://placehold.it/32x32',
    age: 21,
    name: {
      first: 'Laurel',
      last: 'Green',
    },
    company: 'ZENTIA',
    email: 'laurel.green@zentia.biz',
    address: '454 Fayette Street, Brogan, Rhode Island, 2234',
    tags: ['in', 'occaecat', 'aliquip', 'cupidatat', 'nulla'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933eaafdd3fbb26f10a5',
    isActive: false,
    balance: '$3,911.37',
    picture: 'http://placehold.it/32x32',
    age: 25,
    company: 'FROSNEX',
    email: 'rutledge.snider@frosnex.net',
    address: '610 Miller Avenue, Oasis, Utah, 8781',
    tags: ['consequat', 'incididunt', 'excepteur', 'anim', 'dolore'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933ebc3476bdbef397c2',
    isActive: false,
    balance: '$2,971.23',
    picture: 'http://placehold.it/32x32',
    age: 32,
    name: {
      first: 'Lindsey',
      last: 'Trujillo',
    },
    company: 'TETRATREX',
    email: 'lindsey.trujillo@tetratrex.com',
    address: '762 Will Place, Dola, Tennessee, 2751',
    tags: ['adipisicing', 'ullamco', 'quis', 'sint', 'labore'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e1eb2011d7fd8c0bc',
    isActive: false,
    balance: '$1,500.72',
    picture: 'http://placehold.it/32x32',
    age: 22,
    name: {
      first: 'Leach',
      last: 'Hopkins',
    },
    company: 'CUBICIDE',
    email: 'leach.hopkins@cubicide.me',
    address: '491 Arkansas Drive, Marshall, New York, 9123',
    tags: ['qui', 'quis', 'consequat', 'sint', 'ad'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933ede28958cc504b98e',
    isActive: false,
    balance: '$2,475.08',
    picture: 'http://placehold.it/32x32',
    age: 37,
    name: {
      first: 'Terrie',
      last: 'Bernard',
    },
    email: 'terrie.bernard@zilodyne.co.uk',
    address: '292 Bushwick Place, Buxton, Kansas, 5301',
    tags: ['deserunt', 'aliquip', 'nisi', 'proident', 'dolore'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e1a07fdb14cc96fa3',
    isActive: false,
    balance: '$2,943.52',
    picture: 'http://placehold.it/32x32',
    age: 25,
    name: {
      first: 'Lillie',
      last: 'Gardner',
    },
    company: 'NEUROCELL',
    email: 'lillie.gardner@neurocell.org',
    address: '988 Sutton Street, Eastvale, Oklahoma, 1840',
    tags: ['eiusmod', 'in', 'in', 'proident', 'consectetur'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933edb34d2b8cc2af942',
    isActive: false,
    balance: '$2,274.04',
    picture: 'http://placehold.it/32x32',
    age: 26,
    name: {
      first: 'Julianne',
      last: 'Simmons',
    },
    company: 'GOLOGY',
    email: 'julianne.simmons@gology.ca',
    address: '105 Kenilworth Place, Snelling, Missouri, 616',
    tags: ['ipsum', 'labore', 'minim', 'commodo', 'incididunt'],
    favoriteFruit: 'banana',
  },
  {
    _id: '5fe1933e6fb05bcbc3fd6ec1',
    isActive: false,
    balance: '$2,049.35',
    picture: 'http://placehold.it/32x32',
    age: 23,
    name: {
      first: 'Ramos',
      last: 'Riggs',
    },
    company: 'DANCITY',
    email: 'ramos.riggs@dancity.info',
    address: '779 Irwin Street, Mathews, South Carolina, 9881',
    tags: ['eiusmod', 'incididunt', 'eu', 'ad', 'in'],
    favoriteFruit: 'strawberry',
  },
  {
    _id: '5fe1933e9c286f41bb569be5',
    isActive: false,
    balance: '$2,694.08',
    picture: 'http://placehold.it/32x32',
    age: 30,
    name: {
      first: 'Lenore',
      last: 'Vasquez',
    },
    company: 'CONCILITY',
    email: 'lenore.vasquez@concility.tv',
    address: '904 Jackson Street, Emerald, Colorado, 548',
    tags: ['tempor', 'qui', 'proident', 'consectetur', 'sit'],
    favoriteFruit: 'apple',
  },
  {
    _id: '5fe1933e69d41929f715253b',
    isActive: true,
    balance: '$3,272.72',
    picture: 'http://placehold.it/32x32',
    age: 36,
    name: {
      first: 'Burch',
      last: 'Leblanc',
    },
    company: 'OPTICON',
    email: 'burch.leblanc@opticon.name',
    address: '842 Pleasant Place, Defiance, Kentucky, 3442',
    tags: ['laborum', 'non', 'ullamco', 'Lorem', 'reprehenderit'],
    favoriteFruit: 'apple',
  },
];
